create table reminders (
    reminder_id integer generated by default as identity (sequence name reminder_id_seq),
    deadline timestamp(0) not null,
    description varchar(2000) not null
);

create unique index reminders_pk_i on reminders (reminder_id);

alter table reminders add constraint reminders_pk primary key (reminder_id);
